### ISSUE TITLE
MyTLC no longer available on app store

### ISSUE THREAD

**Issue by ds6** [masonmilby/MyTLC-Android#1]
An update was pushed today (version 40 -> 41). Thereafter, the app was removed from the store.
![screenshot_yalp_store_20180711-180812](https://user-images.githubusercontent.com/16788697/42603906-7fcf14fc-8535-11e8-9757-ec65656de199.png)

**Comment by masonmilby** [comment]
The update was to inform users that Best Buy has requested the removal of both of my apps. It was not compromised.

**Comment by ds6** [comment]
I assumed based on what I heard later. Would have been nice if there was a replacement immediately available.
